-- add_users_table (and core gateway tables)
-- Generated by: supabase migration new add_users_table

-- Extensions
create extension if not exists pgcrypto;

-- Public user profile table (mirrors auth.users)
create table if not exists public.users (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  display_name text,
  created_at timestamptz not null default now()
);

alter table public.users enable row level security;

create policy "users_self_select"
  on public.users for select
  using (auth.uid() = id);

create policy "users_self_insert"
  on public.users for insert
  with check (auth.uid() = id);

create policy "users_self_update"
  on public.users for update
  using (auth.uid() = id)
  with check (auth.uid() = id);

-- API keys issued by our gateway (never store raw secret)
create table if not exists public.api_keys (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  key_prefix text not null,
  key_hash text not null unique,
  name text,
  status text not null default 'active',
  rate_limit_rps integer not null default 3,
  rate_limit_burst integer not null default 10,
  created_at timestamptz not null default now(),
  expires_at timestamptz
);
create index if not exists api_keys_user_id_idx on public.api_keys(user_id);
create index if not exists api_keys_status_idx on public.api_keys(status);

alter table public.api_keys enable row level security;

create policy "api_keys_owner_select"
  on public.api_keys for select
  using (auth.uid() = user_id);

create policy "api_keys_owner_insert"
  on public.api_keys for insert
  with check (auth.uid() = user_id);

create policy "api_keys_owner_update"
  on public.api_keys for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "api_keys_owner_delete"
  on public.api_keys for delete
  using (auth.uid() = user_id);

-- Provider credentials (BYOK) per user/provider/name
-- encrypted_key: base64(nonce||ciphertext) from AES-256-GCM
create table if not exists public.provider_credentials (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  provider text not null,
  name text not null default 'default',
  encrypted_key text not null,
  created_at timestamptz not null default now(),
  unique (user_id, provider, name)
);
create index if not exists provider_credentials_user_idx on public.provider_credentials(user_id);

alter table public.provider_credentials enable row level security;

create policy "provider_creds_owner_select"
  on public.provider_credentials for select
  using (auth.uid() = user_id);

create policy "provider_creds_owner_insert"
  on public.provider_credentials for insert
  with check (auth.uid() = user_id);

create policy "provider_creds_owner_update"
  on public.provider_credentials for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "provider_creds_owner_delete"
  on public.provider_credentials for delete
  using (auth.uid() = user_id);

-- Usage events (analytics / billing)
create table if not exists public.usage_events (
  id bigserial primary key,
  api_key_id uuid references public.api_keys(id) on delete set null,
  user_id uuid not null,
  provider text not null,
  model text,
  input_tokens integer,
  output_tokens integer,
  cost_usd numeric(12,6),
  status_code integer,
  created_at timestamptz not null default now()
);
create index if not exists usage_events_user_created_idx on public.usage_events(user_id, created_at desc);
create index if not exists usage_events_api_key_idx on public.usage_events(api_key_id);

alter table public.usage_events enable row level security;

create policy "usage_owner_select"
  on public.usage_events for select
  using (auth.uid() = user_id);




